### ISSUE TITLE
big bug

### ISSUE THREAD

**Issue by johnjackson** [adamlacombe/Shadow-DOM-inject-styles#5] opened 2019-11-21 08:47 UTC
there is a bug: if there isn't any <style> tag in the shadowRootElement, this function can't work, because it use forEach of style tag elements.

**Comment by cns-dan** [comment] 2019-11-27 14:58
Duplicate of #4

**Comment by adamlacombe** [comment] 2020-06-11 15:22
Resolved in https://github.com/adamlacombe/Shadow-DOM-inject-styles/pull/6

Try version 1.0.3

**Closed as completed** 2020-06-11 15:23 UTC
